This Programming assignment is for basic understanding of usage of numpy library for doing math operations on vectors, metrices etc.

1.1 Sigmoid
Exercise: Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.

Reminder: sigmoid(x)=1/(1+e^−x)
 is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

In [1]:
import math

def sigmoid(x):
    sig = 1/(1+math.exp(-x))
    return sig


In [2]:
sigmoid(3)

0.9525741268224334

Above function is useful for real num but if we pass vector, then it wont run so...

In [3]:
import numpy as np

def sigmoid_np(x):
    s = 1/(1+np.exp(-x))
    return s



In [4]:
sigmoid_np(np.array([1,2,3]))

array([0.73105858, 0.88079708, 0.95257413])

1.2 - Sigmoid gradient
As you've seen in lecture, you will need to compute gradients to optimize loss functions using backpropagation. Let's code your first gradient function.

Exercise: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is:
sigmoid_derivative(x)=σ′(x)=σ(x)(1−σ(x))(2)
You often code this function in two steps:

Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
Compute σ′(x)=s(1−s)

In [5]:
def sigmoid_derivative(x):
    s = sigmoid_np(x)
    ds = s*(1-s)
    return ds

In [6]:
a = np.array([1,2,3])
print("sigmoid derivative " , sigmoid_derivative(a))

sigmoid derivative  [0.19661193 0.10499359 0.04517666]


1.3 Reshape
Exercise: Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1). For example, if you would like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:

v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
Please don't hardcode the dimensions of image as a constant. Instead look up the quantities you need with image.shape[0], etc.

In [7]:
def image2vector(image):
    w,h,c = image.shape
    img = image.reshape(w*h*c, 1)
    return img

In [8]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


1.4 - Normalizing rows
Another common technique we use in Machine Learning and Deep Learning is to normalize our data. It often leads to a better performance because gradient descent converges faster after normalization. Here, by normalization we mean changing x to x∥x∥
 (dividing each row vector of x by its norm).

For example, if
x=[023644](3)
then
∥x∥=np.linalg.norm(x,axis=1,keepdims=True)=[556−−√](4)
and
x_normalized=x∥x∥=[0256√35656√45456√](5)
Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 5.

Exercise: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [9]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x/x_norm
    return x

In [10]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


1.5 - Broadcasting and the softmax function
A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical operations between arrays of different shapes. For the full details on broadcasting, you can read the official broadcasting documentation.

Exercise: Implement a softmax function using numpy. You can think of softmax as a normalizing function used when your algorithm needs to classify two or more classes. You will learn more about softmax in the second course of this specialization.

In [11]:
def softmax(x):
    x_exp = np.exp(x)
    #print(x_exp)
    x_sum = np.sum(x_exp, axis = 1, keepdims=True)
    #print(x_sum)
    s = x_exp/x_sum # broadcasting is used x_exp is of dimension x(m X n), x_sum is of dimension (m X 1)
    return s

In [12]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


2) Vectorization
In deep learning, you deal with very large datasets. Hence, a non-computationally-optimal function can become a huge bottleneck in your algorithm and can result in a model that takes ages to run. To make sure that your code is computationally efficient, you will use vectorization. For example, try to tell the difference between the following implementations of the dot/outer/elementwise product.

In [15]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#classical dot product
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print("dot = " + str(dot) + "\n  computation time = " + str((toc-tic)*1000) + "ms")

#classical outer product
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
#outer = np.zeros((len(x1)),(len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i, j] = x1[i]*x2[j]
toc = time.process_time()
print("outer = " + str(outer) + "\n  computation time = " + str((toc-tic)*1000) + "ms")

#classical elementwise
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]

toc = time.process_time()
print("elementwise multiplication = " + str(mul) + "\n  computation time = " + str((toc-tic)*1000) + "ms")

#classical general dot product
W=np.random.rand(3, len(x1))
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] = W[i, j]*x1[j]

toc = time.process_time()
print("General dot product multiplication = " + str(gdot) + "\n  computation time = " + str((toc-tic)*1000) + "ms")




dot = 278
  computation time = 0.0ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
  computa

In [16]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " + str(dot) + "\n  computation time = " + str((toc-tic)*1000) + "ms")


tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("dot = " + str(outer) + "\n  computation time = " + str((toc-tic)*1000) + "ms")

tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print("dot = " + str(mul) + "\n  computation time = " + str((toc-tic)*1000) + "ms")


tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print("dot = " + str(dot) + "\n  computation time = " + str((toc-tic)*1000) + "ms")

dot = 278
  computation time = 0.0ms
dot = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
  computation time = 0.0ms
dot = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
  computation time = 0.0ms
dot = [23.91541195 24.0236056  21.63780984]
  computation time = 0.0ms


2.1 Implement the L1 and L2 loss functions
Exercise: Implement the numpy vectorized version of the L1 loss. You may find the function abs(x) (absolute value of x) useful.

Reminder:

The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions (y^
) are from the true values (y
). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.
L1 loss is defined as:
L1(y^,y)=∑i=0m|y(i)−y^(i)

Exercise: Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if x=[x1,x2,...,xn]
, then np.dot(x,x) = ∑nj=0x2j
.

L2 loss is defined as
L2(y^,y)=∑i=0m(y(i)−y^(i))2

In [22]:
def L1(yhat, y):
    s = sum(abs(yhat-y))
    return s

def L2(yhat, y):
    x = yhat-y
    s = np.dot(x,x)
    return s

In [23]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))
print("L2 = " + str(L2(yhat,y)))

L1 = 1.1
L2 = 0.43
